In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.16.4


In [3]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
print("%d bytes" % (z.size * z.itemsize))

80 bytes


In [5]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [6]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
z = np.arange(10)
z = z[::-1]
print(z)

[9 8 7 6 5 4 3 2 1 0]


In [10]:
z = np.arange(9).size(3,3)
print(z)

TypeError: 'int' object is not callable

In [11]:
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
z = np.nonzero([1,2,0,0,4,0])
print(z)

(array([0, 1, 4], dtype=int64),)


In [13]:
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
z = np.random.randn((3,3,3))
print(z)

TypeError: 'tuple' object cannot be interpreted as an integer

In [15]:
z = np.random.random((3,3,3))
print(z)

[[[0.93290796 0.41120721 0.64087259]
  [0.98982335 0.25303671 0.84120899]
  [0.98502948 0.94926433 0.47071501]]

 [[0.63159491 0.60397709 0.03811095]
  [0.15480738 0.59489738 0.14721427]
  [0.3622667  0.18009843 0.73407026]]

 [[0.17468597 0.23274996 0.18251434]
  [0.46603214 0.61998132 0.99055781]
  [0.40103267 0.90734568 0.01192582]]]


In [16]:
z = np.random.random((10,10))
zmin,zmax = z.min(),z.max()
print(zmin,zmax)

0.007559797388268841 0.9925175937360802


In [17]:
z = np.random.random(30)
s = z.mean()
print(s)

0.44753966803364575


In [18]:
z = np.ones((5,5))
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
z = np.ones((5,5))
z = np.pad(z,pad_width=1,mode='constant',constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [23]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3 == 0.1*3)

nan
False
False
nan
False


In [24]:
z = np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [25]:
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [26]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [27]:
z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [30]:
z = np.random.random((5,5))
zmin,zmax = z.min(),z.max()
z = (z-zmin)/(zmax-zmin)
print(z)

[[0.75724274 0.46294928 0.94359657 1.         0.06150691]
 [0.         0.38004436 0.36756601 0.34417918 0.79180308]
 [0.50982648 0.44396794 0.10019542 0.98066549 0.82517541]
 [0.10678227 0.80274879 0.37961803 0.16729816 0.55420534]
 [0.89324402 0.26548196 0.35484061 0.98336549 0.86489881]]


In [32]:
color = np.dtype([("r",np.dtype,1),("g",np.dtype,1),("b",np.dtype,1),("a",np.dtype,1)])
print(color)

[('r', 'O'), ('g', 'O'), ('b', 'O'), ('a', 'O')]


In [33]:
z = np.dot(np.ones((5,3)),np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [34]:
z = np.arange(1,10)
z[(3 <= z) & (z <= 8 )]*= -1
print(z)

[ 1  2 -3 -4 -5 -6 -7 -8  9]


In [35]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [36]:
z = np.arange(5)
z ** z

array([  1,   1,   4,  27, 256], dtype=int32)

In [37]:
2 << z >> 2


array([0, 1, 2, 4, 8], dtype=int32)

In [38]:
z = np.arange(5)
z <- z

array([False, False, False, False, False])

In [39]:
z = np.arange(5)
z/1/1

array([0., 1., 2., 3., 4.])

In [40]:
lj*z

NameError: name 'lj' is not defined

In [41]:
print(np.array(0)/np.array(0))


nan


X:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [42]:
print(np.array(0)//np.array(0))

0


X:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [43]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


In [44]:
z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))

[-3. -1.  9. -7. -8.  6. -1.  8.  2. -8.]


In [45]:
print(z)

[-2.45186905 -0.03807396  8.08225543 -6.22922516 -7.89315548  5.94862803
 -0.58593746  7.42780237  1.74406914 -7.36214939]


In [46]:
print(z)
print(np.copysign(np.ceil(np.abs(z)),z))

[-2.45186905 -0.03807396  8.08225543 -6.22922516 -7.89315548  5.94862803
 -0.58593746  7.42780237  1.74406914 -7.36214939]
[-3. -1.  9. -7. -8.  6. -1.  8.  2. -8.]


In [50]:
z1 = np.random.randint(0,10)
z2 = np.random.randint(0,10)
#print(np.intersected(z1[0,:],z2[0,:]))

AttributeError: module 'numpy' has no attribute 'intersected'

In [51]:
print(np.inetrsect1d(z1,z2))

AttributeError: module 'numpy' has no attribute 'inetrsect1d'

In [52]:
print(np.intersect1d(z1,z2))

[]


In [53]:
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print(np.intersect1d(z1,z2))

[2 4 5 9]


In [54]:
z = np.ones(1)/0

X:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [55]:
defaults = np.seterr(all="igonre")
z = np.ones(1)/0

KeyError: 'igonre'

In [56]:
np.sqrt(-1)

X:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

In [57]:
np.emath.sqrt(-1)

1j

In [58]:
y1 = np.datetime64('today','D')-np.timedelta64(1,'D')
y2 = np.datetime64('today','D')
y3 = np.datetime64('today','D')+np.timedelta64(1,'D')
print(y1)
print(y2)
print(y3)

2019-08-06
2019-08-07
2019-08-08


In [59]:
z = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [60]:
z = arange('2017-03','2019-08',dtype='datetime64[M]')
print(z)

['2017-03' '2017-04' '2017-05' '2017-06' '2017-07' '2017-08' '2017-09'
 '2017-10' '2017-11' '2017-12' '2018-01' '2018-02' '2018-03' '2018-04'
 '2018-05' '2018-06' '2018-07' '2018-08' '2018-09' '2018-10' '2018-11'
 '2018-12' '2019-01' '2019-02' '2019-03' '2019-04' '2019-05' '2019-06'
 '2019-07']


In [64]:
a = np.ones(3)*1
b = np.ones(3)*2
c = np.full((3,3),3)
np.add(a,b,out=b)
print(a)
print(c)

[1. 1. 1.]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [65]:
np.divide(b,2,out=b)

array([1.5, 1.5, 1.5])

In [67]:
np.multiply(b,4,out=a)
print(b)
print(a)

[1.5 1.5 1.5]
[6. 6. 6.]


In [68]:
z = np.random.uniform(0,10,10)
print(z-z%1)
print(np.floor(z))
print(np.ceil(z)-1)
print(z.astype(int))
print(np.trunc(z))

[6. 0. 2. 0. 5. 6. 5. 1. 3. 8.]
[6. 0. 2. 0. 5. 6. 5. 1. 3. 8.]
[6. 0. 2. 0. 5. 6. 5. 1. 3. 8.]
[6 0 2 0 5 6 5 1 3 8]
[6. 0. 2. 0. 5. 6. 5. 1. 3. 8.]


In [69]:
z = np.zeros((5,5))
z +=np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [71]:
def generate():
    for x in range(10):
        yield x
z = np.fromiter(generate(),dtype=float,count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [82]:
z = np.linspace(0,1,12)[1:-1]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [83]:
z = np.random.random(10)
z.sort()
print(z)

[0.27372182 0.31725143 0.36697839 0.38313685 0.39823272 0.45321175
 0.46415895 0.50942278 0.65356834 0.951838  ]


In [84]:
z = np.arange(6)
np.add.reduce(z)

15

In [85]:
a = np.arange(15).reshape((3,5))
b = np.arange(15).reshape((3,5))
d = np.allclose(a,b)
f = np.array_equal(a,b)
print(d)
print(f)

True
True


In [87]:
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

In [88]:
z = np.random.random((10,2))
x,y = z[:,0],z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.57658709 1.22259435 0.13857054 1.11418917 1.13576105 0.95819056
 0.49255913 0.98850176 0.32467055 0.68354973]
[0.89503328 0.66642545 0.59725479 0.90868841 0.61616538 0.73260123
 1.00851201 1.37296966 1.34455214 1.43580174]


In [2]:
z = np.random.random(10)
z[z.argmax()] = 1
print(z)

NameError: name 'np' is not defined

In [1]:
z = np.zeros((5,5),[('x',float),('y',float)])
z['x'],z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(z)

NameError: name 'np' is not defined

In [3]:
import numpy as np
z = np.zeros((5,5),[('x',float),('y',float)])
z['x'],z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [4]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.1636371179666


In [5]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [12]:
np.set_printoptions(threshold=np.nan)
print(z)

AttributeError: module 'numpy' has no attribute 'non'

In [14]:
z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(z-v)).argmin()
print(z[index])

63
